name: Deploy rsbfourth

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Prepare artifacts
        run: |
          mkdir -p deploy_artifacts
          cp -r frontend/dist deploy_artifacts/frontend
          cp backend/target/*.jar deploy_artifacts/backend.jar
          tar -czvf artifacts.tar.gz deploy_artifacts

      - name: Transfer artifacts
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "artifacts.tar.gz"
          target: "/opt/rsbfourth/"

      - name: Execute deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/rsbfourth
            tar -xzvf artifacts.tar.gz
            sudo systemctl stop rsbfourth || true
            cp deploy_artifacts/backend.jar .
            rm -rf frontend
            cp -r deploy_artifacts/frontend .
            sudo chown -R deployer:deployer /opt/rsbfourth
            sudo systemctl start rsbfourth
            rm -rf deploy_artifacts artifacts.tar.gz